icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
info_bg = "#000000"

[[block]]
block = "music"
player = "spotify"
marquee = false
max_width = 25
buttons = ["play", "next"]

[[block]]
block = "sound"
name = "PCM"
driver = "alsa"
step_width = 3

# [[block]]
# block = "net"
# device = "enp0s31f6"
# speed_up = true
# speed_down = true
# interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "used"
show_percentage = true
unit = "Percent"
interval = 20
warning = 75
alert = 90

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
